# Dependabot configuration for Hardy Auth
# This file configures automatic dependency updates for security and maintenance

version: 2
updates:
  # NPM dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "maintainer-team"
    assignees:
      - "security-team"
    labels:
      - "dependencies"
      - "npm"
    milestone: "Dependency Updates"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # Group related updates together
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security-update"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      react:
        patterns:
          - "react*"
          - "@types/react*"
      testing:
        patterns:
          - "vitest"
          - "@vitest/*"
          - "jsdom"
          - "@testing-library/*"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
      next:
        patterns:
          - "next"
          - "@next/*"
      auth:
        patterns:
          - "better-auth"
          - "@better-auth/*"
    # Allow specific updates for security patches
    allow:
      - dependency-type: "all"
      - update-type: "security"
    # Ignore updates for packages we want to control manually
    ignore:
      # Ignore major version updates for core dependencies
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "better-auth"
        update-types: ["version-update:semver-major"]
      - dependency-name: "prisma"
        update-types: ["version-update:semver-major"]
      # Ignore Node.js major version updates
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "devops-team"
    assignees:
      - "maintainer-team"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci/cd"
    commit-message:
      prefix: "ci"
      include: "scope"
    # Group GitHub Actions updates
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    allow:
      - update-type: "security"
      - update-type: "version-update"

  # Docker base image updates (if Dockerfile exists)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "devops-team"
    assignees:
      - "security-team"
    labels:
      - "dependencies"
      - "docker"
      - "security"
    commit-message:
      prefix: "docker"
      include: "scope"
    allow:
      - update-type: "security"
      - update-type: "version-update"