name: Security (Basic)

# Add this after basic CI is working
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security scans every Monday at 2 AM UTC
    - cron: '0 2 * * 1'

jobs:
  basic-security:
    name: Basic Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run npm audit
      run: npm audit --audit-level moderate
      continue-on-error: true

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript
        queries: +security-extended

    - name: Build project (for CodeQL)
      run: npm run build
      env:
        BETTER_AUTH_SECRET: codeql-analysis-secret-32-chars-long
        DATABASE_URL: postgresql://analysis:analysis@localhost/analysis_test

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3